package com.okrutiak.dao;

import com.okrutiak.institution.University;
import com.okrutiak.person.Student;
import com.okrutiak.person.consciousness.Knowledge;
import com.okrutiak.service.UniversityService;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.Scanner;

import static com.okrutiak.service.UniversityService.*;

public class AutoGeneratedUniversityDAO implements UniversityDAO {

    public static final int DEFAULT_NUMBER_OF_STUDENTS = 124;

    @Override
    public University getUniversityByName(String name) {
        University temporary = new University(name);
        for (int i = 0; i < DEFAULT_NUMBER_OF_STUDENTS; i++) {
            temporary.addStudent(new Student((getName()), new Knowledge(getRandom().nextInt(100))));
        }
        return temporary;
    }

    private String getName() {
        InputStream resourceAsStream = this.getClass().getClassLoader().getResourceAsStream("names.txt");
        Scanner s = new Scanner(resourceAsStream);

        ArrayList<String> listNames = new ArrayList<>();
        while (s.hasNext()) {
            listNames.add(s.next());
        }
        s.close();
        resourceAsStream = this.getClass().getClassLoader().getResourceAsStream("fornames.txt");
        s = new Scanner(resourceAsStream);
        ArrayList<String> listFornames = new ArrayList<>();
        while (s.hasNext()) {
            listFornames.add(s.next());
        }
        return listNames.get(UniversityService.getRandom().nextInt(100)) + " " + listFornames.get(UniversityService.getRandom().nextInt(100));
    }


}
