package com.okrutiak.service;

import com.okrutiak.dao.AutoGeneratedUniversityDAO;
import com.okrutiak.dao.UniversityDAO;
import com.okrutiak.institution.University;
import com.okrutiak.person.Student;
import com.okrutiak.person.consciousness.Knowledge;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;


public class UniversityService {

    private UniversityDAO universityDAO = new AutoGeneratedUniversityDAO();

    public List<University> getUniversities() {
        int i = 0;
        System.out.println(universities.get(i++).getName());
        return universities;
    }

    public void setUniversities(List<University> universities) {
        this.universities = universities;
    }

    public static Random getRandom() {
        return random;
    }

    public void setRandom(Random random) {
        this.random = random;
    }

    List<University> universities = new ArrayList<>();
    static Random random = new Random();


    public University createUniversity(String name) {
        University temporary = new University(name);
        universities.add(temporary);
        return temporary;
    }

    public University addStudents(University university,
                                  ArrayList<Student> students) {
        for (int i = 0; i < students.size(); i++) {
            university
                    .addStudent(students.get(i));
        }
        return university;
    }


    public List<Student> getStudentsByUniversityName(String name) {
        return universityDAO.getUniversityByName(name).getStudents();
    }
}

